version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:8080"
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=123$ubhanS
      - DB_NAME=ssisdb
      - SECRET_KEY=${SECRET_KEY:-any_random_secret_key}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - ssis_network
    restart: unless-stopped

  db:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      - MYSQL_DATABASE=ssisdb
      - MYSQL_ROOT_PASSWORD=123$ubhanS
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db_script:/docker-entrypoint-initdb.d
    networks:
      - ssis_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-p123$ubhanS"]
      interval: 5s
      timeout: 5s
      retries: 20

networks:
  ssis_network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
