apiVersion: apps/v1
kind: Deployment
metadata:
  name: ssis-web
  namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ssis-web
  template:
    metadata:
      labels:
        app: ssis-web
    spec:
      containers:
        - name: ssis-web
          # DockerHub User: subhan45
          image: subhan45/ssis-web:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              value: "ssis-db"
            - name: DB_USER
              value: "root"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ssis-secrets
                  key: DB_PASSWORD
            - name: DB_NAME
              value: "ssisdb"
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: ssis-secrets
                  key: SECRET_KEY
            - name: REDIS_URL
              value: "redis://ssis-redis:6379/0"
---
apiVersion: v1
kind: Service
metadata:
  name: ssis-web
  namespace: dev
spec:
  type: LoadBalancer # Or NodePort
  selector:
    app: ssis-web
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30080
