apiVersion: v1
kind: Secret
metadata:
  name: ssis-secrets
  namespace: dev
type: Opaque
data:
  # Base64 encoded values
  # DB_PASSWORD: 123SubhanS -> MTIzU3ViaGFuUw==
  # SECRET_KEY: dev -> ZGV2
  DB_PASSWORD: MTIzU3ViaGFuUw==
  SECRET_KEY: ZGV2
